version: "3"
services:
  backend:
    container_name: g3t-nodeapp
    build:
      dockerfile: Dockerfile
    ports: 
     - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:root@host.docker.internal:3306/zone